######### Foxess Config
### Configuration, Modbus
PORT='port'
BAUDRATE='baudrate'
BYTESIZE='bytesize'
STOPBITS='stopbits'
PARITY='parity'
SENSORS='sensors'
### Names in Configuration
NAME='name'
UNIQUE_ID='unique_id'
ADDRESS='address'
SLAVE='slave'
COUNT='count'
UNIT_OF_MEASUREMENT='unit_of_measurement'
DATA_TYPE='data_type'
SCALE='scale'
PRECISION='precision'
SCAN_INTERVAL='scan_interval'
SCAN_OFFSET='scan_offset'
STATE_CLASS='state_class'
INPUT_TYPE='input_type'
DEVICE_CLASS='device_class'
DEVICE_CLASS_ERROR='error'
DEVICE_CLASS_GIVEN='given_value'
DEVICE_CLASS_BATTERY_VERSION='battery_version'
ERROR_BITS='error_bits'
BIT='bit'
SEVERITY='severity'
FAULT_MESSAGE='fault_message'
NO_ERROR='None'
VALUES='values'
VALUE='value'
MEANING='meaning'
### internally defined
TIMESTAMP='timestamp'
ACTUAL_TIMER='actual_timer'

######### Homematic Config
CCU_ADDRESS='CCU Address'
CCU_PORT='CCU Port'
CCU_USER='CCU User'
CCU_PASSWORD='CCU Password'
CCU_MAPPINGS='Mappings'
CCU_HOMEMATIC_STATUS='Homematic Status'
DEVICE_CLASS_DATA_POINT = 'DP'

### Message for STOP
STOP='STOP'